language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=kinto-master
    - TOX_ENV=functional
    - TOX_ENV=flake8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
matrix:
  include:
    - env:
        - TOX_ENV=functional
          WITH=kinto-master
      install:
        - pip install tox
        - .venv/bin/pip install -U https://github.com/Kinto/kinto/zipball/master
        - make install-kinto
        - make run-kinto &
    - python: 3.5
      env:
        - TOX_ENV=py35
