language: python
python: 3.8
env:
    - TOX_ENV=py38
    - TOX_ENV=kinto-master
    - TOX_ENV=flake8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
matrix:
  include:
    - env:
        - TOX_ENV=functional
          WITH=kinto-master
      install:
        - pip install tox
        - make install-kinto
        - pip install -U https://github.com/Kinto/kinto/tarball/master
        - make run-kinto &
    - env:
        - TOX_ENV=functional
      install:
        - pip install tox
        - make install-kinto
        - make run-kinto &
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
